import type { Metadata } from 'next'
import { GeistSans } from 'geist/font/sans'
import { GeistMono } from 'geist/font/mono'
import { ClerkProvider } from '@clerk/nextjs'

import "./globals.css"
import { Toaster } from '@/components/ui/toaster'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>


      <html lang="en">
        <body className={`${GeistSans.variable} ${GeistMono.variable} font-sans`}>
          <Toaster />
          {children}

        </body>
      </html>
    </ClerkProvider>
  )
}
